"""Locked CSV schemas and controlled vocabularies for the manuscript workflow."""
from __future__ import annotations

from collections import OrderedDict

ALLOWED_DATASETS = {"ml100k", "ml1m", "ml_latest_small"}
ALLOWED_DESCRIPTOR_SOURCES = {"genres", "tags", "tags_genres", "tfidf", "tag_relevance"}
ALLOWED_SPLIT_TYPES = {"random_per_user", "chronological_per_user"}
ALLOWED_MODEL_NAMES = {"item_cf", "user_cf", "biased_mf", "als_mf", "plain_nmf", "coupled_nmf"}
ALLOWED_VARIANT_NAMES = {"ratings_only_nmf", "no_descriptor_sparsity", "coupled_nmf"}
ALLOWED_TEST_NAMES = {"paired_t_test", "wilcoxon_signed_rank"}
ALLOWED_DECISIONS = {"significant", "not_significant"}

SCHEMAS = {
    "dataset_summary": OrderedDict([
        ("statistic", "string"),
        ("value", "string"),
    ]),
    "main_comparison": OrderedDict([
        ("dataset_name", "string"),
        ("model_name", "string"),
        ("rmse", "float"),
        ("rmse_std", "float"),
        ("mae", "float"),
        ("mae_std", "float"),
        ("precision_at_5", "float"),
        ("precision_at_5_std", "float"),
        ("precision_at_10", "float"),
        ("precision_at_10_std", "float"),
        ("recall_at_5", "float"),
        ("recall_at_5_std", "float"),
        ("recall_at_10", "float"),
        ("recall_at_10_std", "float"),
        ("ndcg_at_5", "float"),
        ("ndcg_at_5_std", "float"),
        ("ndcg_at_10", "float"),
        ("ndcg_at_10_std", "float"),
    ]),
    "ablation_results": OrderedDict([
        ("dataset_name", "string"),
        ("variant_name", "string"),
        ("k", "int"),
        ("alpha", "float"),
        ("beta", "float"),
        ("lambda_reg", "float"),
        ("rmse", "float"),
        ("mae", "float"),
        ("precision_at_10", "float"),
        ("recall_at_10", "float"),
        ("ndcg_at_10", "float"),
        ("fidelity_at_2", "float"),
        ("mean_coherence", "float"),
    ]),
    "k_sensitivity": OrderedDict([
        ("dataset_name", "string"),
        ("model_name", "string"),
        ("k", "int"),
        ("rmse", "float"),
        ("mae", "float"),
        ("precision_at_10", "float"),
        ("recall_at_10", "float"),
        ("ndcg_at_10", "float"),
    ]),
    "alpha_sensitivity": OrderedDict([
        ("dataset_name", "string"),
        ("model_name", "string"),
        ("alpha", "float"),
        ("rmse", "float"),
        ("mae", "float"),
        ("precision_at_10", "float"),
        ("recall_at_10", "float"),
        ("ndcg_at_10", "float"),
    ]),
    "sparsity_robustness": OrderedDict([
        ("dataset_name", "string"),
        ("setting_name", "string"),
        ("model_name", "string"),
        ("rmse", "float"),
        ("mae", "float"),
        ("precision_at_10", "float"),
        ("recall_at_10", "float"),
        ("ndcg_at_10", "float"),
    ]),
    "explanation_metrics": OrderedDict([
        ("dataset_name", "string"),
        ("model_name", "string"),
        ("fidelity_at_2", "float"),
        ("fidelity_at_3", "float"),
        ("mean_coherence", "float"),
        ("stability_score", "float"),
    ]),
    "factor_keywords": OrderedDict([
        ("dataset_name", "string"),
        ("factor_id", "int"),
        ("descriptor_1", "string"),
        ("descriptor_2", "string"),
        ("descriptor_3", "string"),
        ("descriptor_4", "string"),
        ("descriptor_5", "string"),
        ("interpretation", "string"),
    ]),
    "case_studies": OrderedDict([
        ("dataset_name", "string"),
        ("user_id", "string"),
        ("item_id", "string"),
        ("item_name", "string"),
        ("score", "float"),
        ("dominant_factors", "string"),
        ("explanation_summary", "string"),
    ]),
    "significance_tests": OrderedDict([
        ("dataset_name", "string"),
        ("comparison", "string"),
        ("metric_name", "string"),
        ("test_used", "string"),
        ("p_value", "float"),
        ("decision", "string"),
    ]),
    "run_level_metrics": OrderedDict([
        ("dataset_name", "string"),
        ("model_name", "string"),
        ("seed", "int"),
        ("k", "int"),
        ("alpha", "float"),
        ("beta", "float"),
        ("lambda_reg", "float"),
        ("rmse", "float"),
        ("mae", "float"),
        ("precision_at_5", "float"),
        ("precision_at_10", "float"),
        ("recall_at_5", "float"),
        ("recall_at_10", "float"),
        ("ndcg_at_5", "float"),
        ("ndcg_at_10", "float"),
    ]),
    "factor_heatmap_matrix_long": OrderedDict([
        ("factor_id", "int"),
        ("descriptor_name", "string"),
        ("weight", "float"),
    ]),
    "split_registry": OrderedDict([
        ("dataset_name", "string"),
        ("seed", "int"),
        ("split_type", "string"),
        ("user_id", "string"),
        ("item_id", "string"),
        ("rating", "float"),
        ("timestamp", "string"),
        ("split", "string"),
    ]),
}
